name = "nau"
main = "worker.js"
compatibility_date = "2024-05-13"
workers_dev = true

[vars]
PROXY_BANK_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/proxyList.txt"
KV_PROXY_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/kvProxyList.json"
REVERSE_PRX_TARGET = "speed.cloudflare.com"
EMBED_ASSETS = "true"

[triggers]
crons = []

[build]
command = ""
watch_dir = "src"

[miniflare]
kv_persist = true
cache_persist = true
