name = "nau"
main = "worker.js"
compatibility_date = "2024-05-13"
workers_dev = true

[vars]
PROXY_BANK_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/proxyList.txt"
KV_PROXY_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/kvProxyList.json"
REVERSE_PROXY_TARGET = "speed.cloudflare.com"

[route]
pattern = "nau.privme.dpdns.org/*"
zone_id = "782fdfef36abf4bb5ace4ef08b87bb16"

[build]
command = ""

[miniflare]
kv_persist = true
cache_persist = true
