name = "nau"
main = "_worker.js"
compatibility_date = "2023-12-01"

[vars]
PROXY_BANK_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/proxyList.txt"
KV_PROXY_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/kvProxyList.json"
REVERSE_PROXY_TARGET = "google.com"

[observability]
enabled = true
