name = "nau"
main = "worker.js"
compatibility_date = "2024-05-13"
workers_dev = true

[vars]
KV_PROXY_URL = "https://raw.githubusercontent.com/Trojan949/nau/main/kvProxyList.json"
REVERSE_PRX_TARGET = "speed.cloudflare.com"
